name: Tests

on:
  push:
    branches:
      - main
      - fix-enum-member-access
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install llvm ruby
          echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

      - name: Install dependencies (Linux/All)
        run: sudo python3 install.py

      - name: Run tests
        run: python3 run_tests.py
